# .github/workflows/ci.yml

name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  validate:
    name: Validate Project
    runs-on: ubuntu-latest

    container:
      # Use an official Node.js image based on Debian 12, ensuring
      # our CI environment matches production.
      image: node:22-bookworm-slim

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # This MUST run before `setup-node` so that the correct Yarn version is used for caching.
      - name: Enable Corepack
        run: corepack enable && corepack prepare yarn@4.9.1 --activate

      - name: Minimal Yarn config
        run: |
          echo "nodeLinker: node-modules" >> .yarnrc.yml

      - name: Set up Node.js and cache dependencies
        uses: actions/setup-node@v4
        with:
          cache: 'yarn'

      # The node:bookworm-slim container is minimal and needs extra dependencies for our tools.
      - name: Install System Dependencies
        run: apt-get update && apt-get install -y jq openssl

      - name: Cache Turborepo artifacts
        uses: actions/cache@v4
        with:
          path: .turbo
          key: debian-turbo-${{ github.sha }}
          restore-keys: |
            debian-turbo-

      - name: Install Dependencies
        # Installs dependencies for all workspaces in the monorepo.
        run: yarn install --immutable

      - name: Run Validation Checks
        run: |
          yarn format:check
          yarn lint:check
          yarn typecheck
          yarn test
          yarn build
